name: CI/CD

on:
  workflow_dispatch:
    # inputs:
    #   env-choice:
    #     type: choice
    #     description: Select the Environment
    #     options:
    #     - dev
    #     - stage
    #     - prod

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1
